version: 2.1
orbs:
  terraform: circleci/terraform@3.6.0
workflows:
  version: 2
  terraform_apply:
    jobs:
      - terraform/apply:
          path: infra/main.tf
          filters:
            branches:
              only: main